version: "3"
services:
  validator:
    image: ghcr.io/zama-ai/ethermint-node:latest
    network_mode: host
    restart: always
      #environment:
      # TODO: figure out what to do with keys,
      # if we don't upload sks it doesn't work
      # - FHEVM_GO_KEYS_DIR=/ethermint/fhevm-keys
    volumes:
      - /home/ubuntu/ethermintd:/ethermint
    command:
      - /ethermint/multi-node-start.sh
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:26657/status" ]
      interval: 30s
      timeout: 10s
      retries: 5
