version: "3"
services:
  validator:
    image: DOCKER_IMAGE
    network_mode: host
    restart: always
    logging:
      driver: awslogs
      options:
        awslogs-region: LOGS_REGION
        awslogs-group: zbc-prod-logs
        awslogs-stream: LOGS_STREAM
        awslogs-create-group: "true"
    environment:
      - FHEVM_GO_KEYS_DIR=/root/.ethermintd/fhevm-keys
      - ZAMA_TESTNET=true
      - KMS_ENDPOINT_ADDR=10.0.0.50:50051
      - CHAINID=SUBSTITUTED_CHAIN_ID
    volumes:
      - /home/ubuntu/ethermintd:/root/.ethermintd
    command:
      - /root/.ethermintd/multi-node-start.sh
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:26657/status" ]
      interval: 30s
      timeout: 10s
      retries: 5
