name: "Pull Request Labeler"
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  triage:
    if: false # Skip, fix in ref: https://github.com/Inco-fhevm/zbc-ethermint/issues/42
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
