name: Publish developer image

on:
  workflow_dispatch:
    inputs:
      ethermint_node_tag:
        description: 'Ethermint node tag (default: latest)'
        default: "latest"
        type: string
        required: false
      tfhe_cli_tag:
        description: 'TFHE CLI tag (default: latest)'
        default: "latest"
        type: string
        required: false
      ref_to_ethermint:
        description: 'Branch, tag or commit SHA1 to checkout Ethermint'
        required: true
        default: "main"
        type: string

env:
  DOCKER_IMAGE: ghcr.io/zama-ai/ethermint-dev-node


jobs:
  push_to_registry:
    name: Push Docker image to GitHub Container Registry
    runs-on: ubuntu-latest
    steps:

      - name: Check out ethermint
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref_to_ethermint }}

      - name: Check OS
        run: |
          lscpu
          uname -r
          lsb_release -a

      - name: Login to GitHub Container Registry
        uses: docker/login-action@49ed152c8eca782a232dede0303416e8f356c37b
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: List files in ethermint
        run: |
          ls docker

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@c47758b77c9736f4b2ef4073d4d51994fabfe349
        with:
          platforms: linux/amd64,linux/arm64

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          build-args: |
            ETHERMINT_NODE_VERSION=${{ inputs.ethermint_node_tag }}
            TFHE_CLI_VERSION=${{ inputs.tfhe_cli_tag }}
          context: .
          file: docker/Dockerfile.ethermint-node.developer
          push: true
          pull: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ env.DOCKER_IMAGE }}:${{ inputs.ethermint_node_tag }},${{ env.DOCKER_IMAGE }}:latest
          labels: dev-image
